version: '3.3'

services:
  web:
    restart: always
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/django_movie
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
    command: python manage.py runserver 0.0.0.0:8000

  db:
    restart: always
    image: postgres:13.4-alpine
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./data/db/redisdata:/data_redis_db

  celery:
    build: .
    command: celery -A django_movie worker -l info
    volumes:
      - .:/usr/src/django_movie
    env_file:
      - ./.env
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A django_movie beat -l info
    volumes:
      - .:/usr/src/django_movie
    env_file:
      - ./.env
    depends_on:
      - redis

  flower:
    build: .
    command: celery flower --port=5555 --broker=redis://redis:6379 --persistent
    ports:
      - 5555:5555
    volumes:
      - .:/usr/src/django_movie
    environment:
      - CELERY_BROKER=redis://redis:6379
      - CELERY_BACKEND=redis://redis:6379
    depends_on:
      - web
      - redis
      - celery

volumes:
  postgres_data:
