# Generated by Django 3.2.6 on 2022-05-09 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20220507_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieImdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.PositiveIntegerField(verbose_name='Unique ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('overview', models.TextField(default='', verbose_name='Overview')),
                ('release_date', models.DateField(default=datetime.date.today, verbose_name='Release date')),
                ('vote_count', models.PositiveIntegerField(default=0, verbose_name='Vote count')),
                ('vote_average', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Vote Average')),
                ('media_type', models.CharField(max_length=100, verbose_name='Media Type')),
            ],
        ),
    ]
